[project]
name = "my-api"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
    "fastapi",
    "uvicorn",
    "python-dotenv",
    "openai",
    "pydantic",
    "beautifulsoup4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.vercel]
entrypoint = "chat:app"
